server:
  port: 8008

spring:
  application:
    name: dorandoran
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    database: postgresql
  profiles:
    include:
      - database
      - jwt
  data:
    redis:
      repositories:
        enabled: false
