server:
  port: 8008

spring:
  application:
    name: dorandoran
  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
  profiles:
    include:
      - database
  data:
    redis:
      repositories:
        enabled: false
